version: '3.8'
services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: mssql
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: ${SA_PASSWORD}
      ACCEPT_EULA: "Y"
    networks:
      - mynetwork

  tailscale:
    image: tailscale/tailscale
    container_name: tailscale
    privileged: true
    networks:
      - mynetwork
    command: tailscaled

networks:
  mynetwork:
    driver: bridge
