version: '3.8'
services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: mssql
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: ${SA_PASSWORD}
      ACCEPT_EULA: "Y"
    networks:
      - mynetwork

  tailscale:
    image: tailscale/tailscale
    container_name: tailscale
    privileged: true
    networks:
      - mynetwork
    environment:
      - TS_AUTH_KEY=${TAILSCALE_API_KEY}tskey-XXXXXXXXXXXXXXXXXXXXXXX # Sostituisci con il tuo Tailscale auth key
    command: ["tailscaled", "--state=/var/lib/tailscale/tailscaled.state"]
    restart: unless-stopped    

networks:
  mynetwork:
    driver: bridge
